/* Generated by https://quicktype.io */

export interface MovieData {
    id:          number;
    name:        string;
    description: string;
    image:       string;
    price:       number;  // Added manually in codealong of 2026-01-30
    genres:      Genre[];
    slug:        string;
}

export interface Genre {
    id:               number;
    title:            string;
    slug:             string;
    poster_genre_rel: PosterGenreRel;
}

export interface PosterGenreRel {
    id:        number;
    poster_id: number;
    genre_id:  number;
}

